### ISSUE TITLE
Query params are not properly encoded

### ISSUE THREAD

**Issue by martinos** [luckymarmot/Paw-HTTPieCodeGenerator#7]
Eg: 
My Paw project generates:

```
http GET http://localhost:3000/api/users/1/fligh_histories?page=1&per_page=10 \
    'X-API-TOKEN':'xxxxxdddffssdfsdf' \
    'X-API-EMAIL':'joe@example.com' \
    'Accept':'application/json'
```

Instead of something like:

```
http GET http://localhost:3000/api/users/1/fligh_histories \
    'X-API-TOKEN':'xxxxxdddffssdfsdf' \
    'X-API-EMAIL':'joe@example.com' \
    'Accept':'application/json' page==1 per_page==10
```

**Comment by JonathanMontane** [comment]
@martinos thanks for the report, I'll look into it!

**Comment by JonathanMontane** [comment]
@martinos both syntaxes are correct, the issue here is that the url is not within quotes, so the `&` character gets evaluated as a shell `&`. I'm fixing it right now, and trying to see if I can find edge cases that would break as a consequence of this change.

**Comment by martinos** [comment]
I did't know that `&` was evaluated while it is not a the end of a line. This makes sense, thanks.

**Comment by JonathanMontane** [comment]
@martinos Glad that I could help! I updated the code generation with PR #8. If you update your extension, it should now be working properly.

**Comment by martinos** [comment]
It works well, thanks again!
